version: "3.8"
name: coworking

services:
  db:
    image: postgres:latest
    container_name: coworking_db
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
